name = "cloudflare"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
B2_BUCKET_ID = ""
B2_APP_KEY_ID = ""
B2_APP_KEY = ""
USER_AGENT = "my-application/0.1.0"

[[durable_objects.bindings]]
name = "SERVER"
class_name = "Server"

[[migrations]]
tag = "v1"
new_classes = ["Server"]
